config/urls.py
from django.contrib import admin
from django.urls import path, include
# from django.conf.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('post/', include('post.urls')),
    path('', include('smoking.urls')),
]

post/urls.py
from django.urls import path
from post.views import post_list, post_detail, post_edit, post_delete, post_new, post_not_allowed, post_confirm_delete, comment_delete, post_list_notice, post_list_questions, post_list_request, post_list_report, post_list_etc

app_name = 'post'

urlpatterns = [
    path('post_list', post_list, name='post_list'),

    path('post_list_notice', post_list_notice, name='post_list_notice'),
    path('post_list_questions', post_list_questions, name='post_list_questions'),
    path('post_list_request', post_list_request, name='post_list_request'),
    path('post_list_report', post_list_report, name='post_list_report'),
    path('post_list_etc', post_list_etc, name='post_list_etc'),

    path('post/<pk>/', post_detail, name='post_detail'),
    path('new/', post_new, name='post_new'),
    path('post/<pk>/edit/', post_edit, name='post_edit'),
    # path('post/<pk>/delete/', post_delete, name='post_delete'),
    path('post_not_allowed', post_not_allowed, name='post_not_allowed'),

    path('post/<pk>/confirm_delete/', post_confirm_delete, name='post_confirm_delete'),
    path('post/<pk>/confirm_delete/delete/', post_delete, name='post_delete'),
    # 댓글 삭제
    path('post/<post_pk>/comment_delete/<comment_pk>', comment_delete, name='comment_delete'),
]

smoking/urls.py
from django.urls import path
from . import views

app_name = 'smoking'

urlpatterns=[

    path('boroughlist/', views.boroughlist, name='borough_list'),
    path('', views.smokingmap, name='smoking_map'),
    path('location/', views.location, name='location'),
    path('cp_cd/', views.cp_cd, name='cp_cd'),

    path('graph/', views.graph, name='graph'),
    path('graph_age/', views.graph_age, name='graph_age'),
    path('graph_cigaretteprice/', views.graph_cigaretteprice, name='graph_cigaretteprice'),

    path('direction/', views.direction, name='direction'),
    path('gangnam_map/', views.gangnam_map, name='gangnam_map'),
    path('gangdong_map/', views.gangdong_map, name='gangdong_map'),
    path('gangbuk_map/', views.gangbuk_map, name='gangbuk_map'),
    path('gangseo_map/', views.gangseo_map, name='gangseo_map'),
    path('gwanak_map/', views.gwanak_map, name='gwanak_map'),
    path('gwangjin_map/', views.gwangjin_map, name='gwangjin_map'),
    path('guro_map/', views.guro_map, name='guro_map'),
    path('geumcheon_map/', views.geumcheon_map, name='geumcheon_map'),
    path('nowon_map/', views.nowon_map, name='nowon_map'),
    path('dobong_map/', views.dobong_map, name='dobong_map'),
    path('dongdaemun_map/', views.dongdaemun_map, name='dongdaemun_map'),
    path('dongjak_map/', views.dongjak_map, name='dongjak_map'),
    path('mapo_map/', views.mapo_map, name='mapo_map'),
    path('seodaemun_map/', views.seodaemun_map, name='seodaemun_map'),
    path('seocho_map/', views.seocho_map, name='seocho_map'),
    path('seongdong_map/', views.seongdong_map, name='seongdong_map'),
    path('seongbuk_map/', views.seongbuk_map, name='seongbuk_map'),
    path('songpa_map/', views.songpa_map, name='songpa_map'),
    path('yangcheon_map/', views.yangcheon_map, name='yangcheon_map'),
    path('yeongdeungpo_map/', views.yeongdeungpo_map, name='yeongdeungpo_map'),
    path('yongsan_map/', views.yongsan_map, name='yongsan_map'),
    path('eunpyeong_map/', views.eunpyeong_map, name='eunpyeong_map'),
    path('jongro_map/', views.jongro_map, name='jongro_map'),
    path('jung_map/', views.jung_map, name='jung_map'),
    path('jungrang_map/', views.jungrang_map, name='jungrang_map'),

    path('fullopen/', views.fullopen, name='fullopen'),
    path('fullclose/', views.fullclose, name='fullclose'),
    path('littleopen/', views.littleopen, name='littleopen'),
    path('etc/', views.etc, name='etc'),
    path('tipoff/', views.tipoff, name='tipoff'),

    path('chart', views.ChartView.as_view(), name="chart"),

]

smoking/models.py
from django.db import models

# Create your models here.


class Borough(models.Model):
    boroughcode = models.AutoField(verbose_name='자치구 코드', primary_key = True)
    boroughname = models.CharField(max_length=64, verbose_name='자치구명')

    class Meta: #메타 클래스를 이용하여 테이블명 지정
        db_table = 'Borough'


class SmokingAreaType(models.Model):
    typecode = models.AutoField(verbose_name='유형 코드', primary_key = True)
    typename = models.CharField(max_length=64, verbose_name='유형 이름')

    class Meta: #메타 클래스를 이용하여 테이블명 지정
        db_table = 'SmokingAreaType'

class SmokingArea(models.Model):
    areacode = models.CharField(max_length=64, verbose_name='구역 코드')
    address = models.CharField(max_length=150, verbose_name='주소')
    boroughcode = models.ForeignKey(Borough, on_delete=models.CASCADE, related_name='borough_smoking', verbose_name='자치구 코드')
    typecode = models.ForeignKey(SmokingAreaType, on_delete=models.CASCADE, related_name='smoking_type', verbose_name='유형 코드')

    class Meta: #메타 클래스를 이용하여 테이블명 지정
        db_table = 'SmokingArea'

class Fine(models.Model):
    finecode = models.AutoField(verbose_name='과태료 코드', primary_key = True)
    finename = models.CharField(max_length=64, verbose_name='과태료 이름')
    finecontents = models.CharField(max_length=100, verbose_name='위반내용')
    fine = models.IntegerField(verbose_name="과태료")

    class Meta: #메타 클래스를 이용하여 테이블명 지정
        db_table = 'Fine'

smoking/views.py
from django.shortcuts import render, HttpResponse
from django.http import HttpResponseRedirect
from django.urls import reverse
from .models import Borough, SmokingArea, SmokingAreaType, Fine
from django.views import generic


def fullopen(request):
    return render(request, 'smoking/fullopen.html')

def fullclose(request):
    return render(request, 'smoking/fullclose.html')

def littleopen(request):
    return render(request, 'smoking/littleopen.html')

def etc(request):
    return render(request, 'smoking/etc.html')

def tipoff(request):
    return render(request, 'smoking/tipoff.html')

def boroughlist(request):
    return render(request, 'smoking/boroughlist.html')

def smokingmap(request):
    return render(request, 'smoking/map.html')

def location(request) :
    return render(request, 'smoking/location.html')

def cp_cd(request) :
    return render(request, 'smoking/cp_cd.html')

def graph(request) :
    return render(request, 'smoking/graph.html')

def graph_age(request) :
    return render(request, 'smoking/graph_age.html')

def graph_cigaretteprice(request) :
    return render(request, 'smoking/graph_cigaretteprice.html')

def direction(request) :
    return render(request, 'smoking/direction.html')

def gangnam_map(request) :
    return render(request, 'smoking/gangnam_map.html')

def gangdong_map(request) :
    return render(request, 'smoking/gangdong_map.html')

def gangbuk_map(request) :
    return render(request, 'smoking/gangbuk_map.html')

def gangseo_map(request) :
    return render(request, 'smoking/gangseo_map.html')

def gwanak_map(request) :
    return render(request, 'smoking/gwanak_map.html')

def gwangjin_map(request) :
    return render(request, 'smoking/gwangjin_map.html')

def guro_map(request) :
    return render(request, 'smoking/guro_map.html')

def geumcheon_map(request) :
    return render(request, 'smoking/geumcheon_map.html')

def nowon_map(request) :
    return render(request, 'smoking/nowon_map.html')

def dobong_map(request) :
    return render(request, 'smoking/dobong_map.html')

def dongdaemun_map(request) :
    return render(request, 'smoking/dongdaemun_map.html')

def dongjak_map(request) :
    return render(request, 'smoking/dongjak_map.html')

def dongdaemun_map(request) :
    return render(request, 'smoking/dongdaemun_map.html')

def mapo_map(request) :
    return render(request, 'smoking/mapo_map.html')

def seodaemun_map(request) :
    return render(request, 'smoking/seodaemun_map.html')

def seocho_map(request) :
    return render(request, 'smoking/seocho_map.html')

def seongdong_map(request) :
    return render(request, 'smoking/seongdong_map.html')

def seongbuk_map(request) :
    return render(request, 'smoking/seongbuk_map.html')

def songpa_map(request) :
    return render(request, 'smoking/songpa_map.html')

def yangcheon_map(request) :
    return render(request, 'smoking/yangcheon_map.html')

def yeongdeungpo_map(request) :
    return render(request, 'smoking/yeongdeungpo_map.html')

def yongsan_map(request) :
    return render(request, 'smoking/yongsan_map.html')

def eunpyeong_map(request) :
    return render(request, 'smoking/eunpyeong_map.html')

def jongro_map(request) :
    return render(request, 'smoking/jongro_map.html')

def jung_map(request) :
    return render(request, 'smoking/jung_map.html')

def jungrang_map(request) :
    return render(request, 'smoking/jungrang_map.html')


from django.views.generic import View
from django.shortcuts import render

class ChartView(View):
    def get(self, request, *args, **kwargs):
        return render(request, 'smoking/cp_cd.html')

smoking/templates/smoking/dobong_map.html
{% extends 'smoking/location_base.html' %}
{% block title %}- 위치/유형 페이지{% endblock %}

{% block content %}

<style>
     .dropup-menu {
        max-height: 400px;
        overflow: hidden;
        overflow-y: auto;
    }

    div#map {margin:0px auto}

     .box {
        position : absolute;
        top : 180px;
        left: 15px;
        width: 97%;

        text-align: center;
        border: 3px solid #57B59A;
        border-radius: 10px;
        padding: 2%;
        background: #FDFFFF;
    }
    .dropup>a {
    background-color: lightgray;
}

.dropup>a:hover {
    background-color: #57B59A;
}
    #map{position:relative;overflow:hidden;}
.dropup, .dropup *{margin:0;color:#000;border-radius: 0;}
.dropup {position:absolute;top:200px;left:28px; z-index:10;text-align:center;background-color:#FFFFFF;}

.typebox {width: 144px; position:absolute; top:10px; right:10px; z-index:10; text-align:center; background-color:#fff; padding : 7px;
          border-radius:10px;}
.smalltype {margin-bottom:3px;}

    @media screen and (max-width: 936px) {
        .container {
            margin-top: 10px;
            margin-bottom: 5px;
        }

        .box2 > .table {
            scroll-behavior: auto;
            font-size: x-small;
            white-space: nowrap;
        }

        .dropup {position:absolute; top:325px;left:20px; z-index:10;text-align:center;background-color:#FFFFFF;}

        .box {
        position : absolute;
        top : 220px;
        left: 15px;
        width: 97%;

        text-align: center;
        border: 3px solid #57B59A;
        border-radius: 10px;
        padding: 2%;
        background: #FDFFFF;
    }

    }
</style>

<div class="container" style="margin-top: 10px">

<div class = "dropup">
        <button style="color:white;" class = "btn btn-secondary dropdown-toggle" data-toggle="dropdown">구 선택</button>
            <a class="dropdown-item" href="{% url 'smoking:gangnam_map' %}" style="height:25px;font-size:13px;">강남구</a>
                <div class="dropdown-divider"></div> <!-- 구분선 -->
            <a class="dropdown-item" href="{% url 'smoking:gangdong_map' %}" style="height:25px;font-size:13px;">강동구</a>
                <div class="dropdown-divider"></div> <!-- 구분선 -->
            <a class="dropdown-item" href="{% url 'smoking:gangbuk_map' %}" style="height:25px;font-size:13px;">강북구</a>
                <div class="dropdown-divider"></div> <!-- 구분선 -->
            <a class="dropdown-item" href="{% url 'smoking:gangseo_map' %}" style="height:25px;font-size:13px;">강서구</a>
                <div class="dropdown-divider"></div> <!-- 구분선 -->
            <a class="dropdown-item" href="{% url 'smoking:gwanak_map' %}" style="height:25px;font-size:13px">관악구</a>
                <div class="dropdown-divider"></div> <!-- 구분선 -->
            <a class="dropdown-item" href="{% url 'smoking:gwangjin_map' %}" style="height:25px;font-size:13px">광진구</a>
                <div class="dropdown-divider"></div> <!-- 구분선 -->
            <a class="dropdown-item" href="{% url 'smoking:guro_map' %}" style="height:25px;font-size:13px">구로구</a>
                <div class="dropdown-divider"></div> <!-- 구분선 -->
            <a class="dropdown-item" href="{% url 'smoking:geumcheon_map' %}" style="height:25px;font-size:13px">금천구</a>
                <div class="dropdown-divider"></div> <!-- 구분선 -->
            <a class="dropdown-item" href="{% url 'smoking:nowon_map' %}" style="height:25px;font-size:13px">노원구</a>
                <div class="dropdown-divider"></div> <!-- 구분선 -->
            <a class="dropdown-item" href="{% url 'smoking:dobong_map' %}" style="height:25px;font-size:13px">도봉구</a>
                <div class="dropdown-divider"></div> <!-- 구분선 -->
            <a class="dropdown-item" href="{% url 'smoking:dongdaemun_map' %}" style="height:25px;font-size:13px">동대문구</a>
                <div class="dropdown-divider"></div> <!-- 구분선 -->
            <a class="dropdown-item" href="{% url 'smoking:dongjak_map' %}" style="height:25px;font-size:13px">동작구</a>
                <div class="dropdown-divider"></div> <!-- 구분선 -->
            <a class="dropdown-item" href="{% url 'smoking:mapo_map' %}" style="height:25px;font-size:13px">마포구</a>
                <div class="dropdown-divider"></div> <!-- 구분선 -->
            <a class="dropdown-item" href="{% url 'smoking:seodaemun_map' %}" style="height:25px;font-size:13px">서대문구</a>
                <div class="dropdown-divider"></div> <!-- 구분선 -->
            <a class="dropdown-item" href="{% url 'smoking:seocho_map' %}" style="height:25px;font-size:13px">서초구</a>
                <div class="dropdown-divider"></div> <!-- 구분선 -->
            <a class="dropdown-item" href="{% url 'smoking:seongdong_map' %}" style="height:25px;font-size:13px">성동구</a>
                <div class="dropdown-divider"></div> <!-- 구분선 -->
            <a class="dropdown-item" href="{% url 'smoking:seongbuk_map' %}" style="height:25px;font-size:13px">성북구</a>
                <div class="dropdown-divider"></div> <!-- 구분선 -->
            <a class="dropdown-item" href="{% url 'smoking:songpa_map' %}" style="height:25px;font-size:13px">송파구</a>
                <div class="dropdown-divider"></div> <!-- 구분선 -->
            <a class="dropdown-item" href="{% url 'smoking:yangcheon_map' %}" style="height:25px;font-size:13px">양천구</a>
                <div class="dropdown-divider"></div> <!-- 구분선 -->
            <a class="dropdown-item" href="{% url 'smoking:yeongdeungpo_map' %}" style="height:25px;font-size:13px">영등포구</a>
                <div class="dropdown-divider"></div> <!-- 구분선 -->
            <a class="dropdown-item" href="{% url 'smoking:yongsan_map' %}" style="height:25px;font-size:13px">용산구</a>
                <div class="dropdown-divider"></div> <!-- 구분선 -->
            <a class="dropdown-item" href="{% url 'smoking:eunpyeong_map' %}" style="height:25px;font-size:13px">은평구</a>
                <div class="dropdown-divider"></div> <!-- 구분선 -->
            <a class="dropdown-item" href="{% url 'smoking:jongro_map' %}" style="height:25px;font-size:13px">종로구</a>
                <div class="dropdown-divider"></div> <!-- 구분선 -->
            <a class="dropdown-item" href="{% url 'smoking:jung_map' %}" style="height:25px;font-size:13px">중구</a>
                <div class="dropdown-divider"></div> <!-- 구분선 -->
            <a class="dropdown-item" href="{% url 'smoking:jungrang_map' %}" style="height:25px;font-size:13px">중랑구</a>
       </div>

</div>

<div class="box" align="center">
    <br/>
    <h4><strong>도봉구 흡연구역 상세 지도</strong></h4>
    <sub>해당 자치구는 흡연구역 데이터가 <strong>제공되지 않는</strong> 구역입니다.</sub><br/><br/>
<script type="text/javascript" src="//dapi.kakao.com/v2/maps/sdk.js?appkey=541b6d15b257b828a3da0c50a02d541e"></script>

<div id="map" style="width:100%;height:600px;">
    <div class="typebox">
            <div class="smalltype"><img style="width:32px; height:32px;" src="https://user-images.githubusercontent.com/73709089/140315617-3954363c-15c7-4054-88ae-3f27022fb89f.png">완전폐쇄형 </div>
            <div class="smalltype"><img style="width:32px; height:32px;" src="https://user-images.githubusercontent.com/73709089/140315629-ae6791aa-13fc-4bcb-83a6-909d849abebf.png">완전개방형 </div>
            <div class="smalltype"><img style="width:32px; height:32px;" src="https://user-images.githubusercontent.com/73709089/140315641-718e9afd-e90b-48d4-9502-96404a2b76b8.png">부분개방형 </div>
            <div class="smalltype"><img style="width:32px; height:32px;" src="https://user-images.githubusercontent.com/73709089/140315652-89c32358-efcb-4104-8b0d-0380732209b8.png">&nbsp&nbsp&nbsp&nbsp&nbsp기타&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp </div>
            <div class="smalltype"><img style="width:32px; height:32px;" src="https://user-images.githubusercontent.com/73293902/141927239-f103e600-4403-4ed4-98c1-e59a7bc4d18e.png">&nbsp&nbsp&nbsp&nbsp&nbsp제보&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp </div>
    </div>
</div>
<br/><br/>

<script>
var mapContainer = document.getElementById('map'), // 지도를 표시할 div
    mapOption = {
        center: new kakao.maps.LatLng(37.6687735, 127.0448823), // 지도의 중심좌표
        level: 5 // 지도의 확대 레벨
    };

var map = new kakao.maps.Map(mapContainer, mapOption); // 지도를 생성합니다

var positions = [

];

// 마커 이미지의 이미지 주소입니다
var imageSrc = "https://t1.daumcdn.net/localimg/localimages/07/mapapidoc/markerStar.png";

for (var i = 0; i < positions.length; i ++) {

    // 마커 이미지의 이미지 크기 입니다
    var imageSize = new kakao.maps.Size(24, 35);

    // 마커 이미지를 생성합니다
    var markerImage = new kakao.maps.MarkerImage(imageSrc, imageSize);

    // 마커를 생성합니다
    var marker = new kakao.maps.Marker({
        map: map, // 마커를 표시할 지도
        position: positions[i].latlng, // 마커를 표시할 위치
        title : positions[i].title, // 마커의 타이틀, 마커에 마우스를 올리면 타이틀이 표시됩니다
        image : markerImage // 마커 이미지
    });
}
</script>
</div>
{% endblock %}

smoking/templates/smoking/tipoff.html
{% extends 'base.html' %}
{% block title %}- 지도 페이지{% endblock %}

{% block content %}

<style>
    #map {margin:0px auto;}

    .box {
    position : absolute;
    top : 180px;
    left: 15px;
    width: 97%;

    text-align: center;
    border: 3px solid #57B59A;
    border-radius: 10px;
    padding: 2%;
    background: #FDFFFF;
    }

#map{position:relative;overflow:hidden;}
.dropdown, .dropdown *{margin:0;color:#000;border-radius: 0;}
.dropdown {position:absolute;top:10px;left:10px;z-index:10;text-align:center;background-color:#fff;}

.typebox {width: 144px; position:absolute; top:10px; right:10px; z-index:10; text-align:center; background-color:#fff; padding : 7px;
          border-radius:10px;}
.smalltype {margin-bottom:3px;}
</style>

<br>

<div class="box">
<script type="text/javascript" src="//dapi.kakao.com/v2/maps/sdk.js?appkey=541b6d15b257b828a3da0c50a02d541e"></script>

<!-- 지도가 표시될 div -->
    <!-- 지도 위에 표시될 드롭다운 -->
    <div id="map" style="width:100%;height:500px;">
        <div class = "dropdown">
            <button class = "btn btn-secondary dropdown-toggle" data-toggle="dropdown" style="color:white;">제보</button>
            <div class="dropdown-menu">
              <a class="dropdown-item" href="{% url 'smoking:fullclose' %}">완전폐쇄형</a>
                <div class="dropdown-divider"></div> <!-- 구분선 -->
              <a class="dropdown-item" href="{% url 'smoking:fullopen' %}">완전개방형</a>
                <div class="dropdown-divider"></div> <!-- 구분선 -->
              <a class="dropdown-item" href="{% url 'smoking:littleopen' %}">부분개방형</a>
                <div class="dropdown-divider"></div> <!-- 구분선 -->
              <a class="dropdown-item" href="{% url 'smoking:etc' %}">기타</a>
                <div class="dropdown-divider"></div> <!-- 구분선 -->
              <a class="dropdown-item" href="{% url 'smoking:tipoff' %}">제보</a>
            </div>
        </div>
    </div>

<!-- 현재 내 위치 찾기-->
<script>
var mapContainer = document.getElementById('map'), // 지도를 표시할 div
    mapOption = {
        center: new kakao.maps.LatLng(33.450701, 126.570667), // 지도의 중심좌표
        level: 4 // 지도의 확대 레벨
    };

var map = new kakao.maps.Map(mapContainer, mapOption); // 지도를 생성합니다

// HTML5의 geolocation으로 사용할 수 있는지 확인합니다
if (navigator.geolocation) {
    // GeoLocation을 이용해서 접속 위치를 얻어옵니다
    navigator.geolocation.getCurrentPosition(function(position) {

        var lat = position.coords.latitude, // 위도
            lon = position.coords.longitude; // 경도

        var locPosition = new kakao.maps.LatLng(lat, lon), // 마커가 표시될 위치를 geolocation으로 얻어온 좌표로 생성합니다
            message = '<div style="padding:5px;">여기에 계신가요?!</div>'; // 인포윈도우에 표시될 내용입니다

        // 마커와 인포윈도우를 표시합니다
        displayMarker(locPosition, message);
     });
} else { // HTML5의 GeoLocation을 사용할 수 없을때 마커 표시 위치와 인포윈도우 내용을 설정합니다
    var locPosition = new kakao.maps.LatLng(33.450701, 126.570667),
        message = 'geolocation을 사용할수 없습니다'

    displayMarker(locPosition, message);
}

// 지도에 마커와 인포윈도우를 표시하는 함수입니다
function displayMarker(locPosition, message) {
    // 마커를 생성합니다
    var marker = new kakao.maps.Marker({
        map: map,
        position: locPosition
    });
    var iwContent = '<div style="padding:5px;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;내위치</div>', // 인포윈도우에 표출될 내용으로 HTML 문자열이나 document element가 가능합니다
    iwPosition = new kakao.maps.LatLng(37.517992740481354, 126.91623783861414); //인포윈도우 표시 위치입니다

    var infowindow = new kakao.maps.InfoWindow({
    position : iwPosition,
    content : iwContent
    });

    // 인포윈도우를 마커위에 표시합니다
    infowindow.open(map, marker);

    // 지도 중심좌표를 접속위치로 변경합니다
    map.setCenter(locPosition);
}

var tipoffpositions = [
    {
        title: '한양여대 뒤 편의점 가는 길', // 1
        content: '<div style="padding:15px;width:350px;text-align: center;">한양여대 뒤 편의점 가는 길<br>제보<br><a href="http://kko.to/keFK_qxfM">길찾기</a></div>',
        latlng: new kakao.maps.LatLng(37.559909, 127.049338), // 1 좌표
        category : '제보'
    },
     {
        title: '한양여대 식품영양관 뒤 주차장', // 2
        content: '<div style="padding:15px;width:350px;text-align: center;">한양여대 식품영양관 뒤 주차장<br>제보<br><a href="">길찾기</a></div>',
        latlng: new kakao.maps.LatLng(37.558798, 127.048314), // 2 좌표
        category : '제보'
    }
];

// 제보 마커 이미지의 이미지 주소입니다
var toimageSrc = "https://user-images.githubusercontent.com/73293902/141927239-f103e600-4403-4ed4-98c1-e59a7bc4d18e.png";

for (var i = 0; i < tipoffpositions.length; i ++) {

    // 마커 이미지의 이미지 크기 입니다
    var imageSize = new kakao.maps.Size(36, 36);

    // 마커 이미지를 생성합니다
    var tomarkerImage = new kakao.maps.MarkerImage(toimageSrc, imageSize);

    // 마커를 생성합니다
    var marker = new kakao.maps.Marker({
        map: map, // 마커를 표시할 지도
        position: tipoffpositions[i].latlng, // 마커를 표시할 위치
        image : tomarkerImage // 마커 이미지
    });

    // 마커에 표시할 인포윈도우를 생성합니다
    var infowindow = new kakao.maps.InfoWindow({
        content: tipoffpositions[i].content, // 인포윈도우에 표시할 내용
        removable:true
    });

    // 마커에 mouseover 이벤트와 mouseout 이벤트를 등록합니다
    // 이벤트 리스너로는 클로저를 만들어 등록합니다
    // for문에서 클로저를 만들어 주지 않으면 마지막 마커에만 이벤트가 등록됩니다
    kakao.maps.event.addListener(marker, 'click', makeOverListener(map, marker, infowindow));
}

// 인포윈도우를 표시하는 클로저를 만드는 함수입니다
function makeOverListener(map, marker, infowindow) {
    return function() {
        infowindow.open(map, marker);
    };
}

// 인포윈도우를 닫는 클로저를 만드는 함수입니다
function makeOutListener(infowindow) {
    return function() {
        infowindow.close();
    };
}
</script>

</div>

</div>


{% endblock %}