accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_view
from .views import register
from . import views

app_name = 'accounts'

urlpatterns = [
   path('register/', register, name='register'),
   path('logout/', auth_view.LogoutView.as_view(template_name='registration/logout.html'), name='logout'),
   path('login/', auth_view.LoginView.as_view(), name='login'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
# from django.conf.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('post/', include('post.urls')),
    path('', include('smoking.urls')),
]

post/urls.py
from django.urls import path
from post.views import post_list, post_detail, post_edit, post_delete, post_new, post_not_allowed, post_confirm_delete, comment_delete, post_list_notice, post_list_questions, post_list_request, post_list_report, post_list_etc

app_name = 'post'

urlpatterns = [
    path('post_list', post_list, name='post_list'),

    path('post_list_notice', post_list_notice, name='post_list_notice'),
    path('post_list_questions', post_list_questions, name='post_list_questions'),
    path('post_list_request', post_list_request, name='post_list_request'),
    path('post_list_report', post_list_report, name='post_list_report'),
    path('post_list_etc', post_list_etc, name='post_list_etc'),

    path('post/<pk>/', post_detail, name='post_detail'),
    path('new/', post_new, name='post_new'),
    path('post/<pk>/edit/', post_edit, name='post_edit'),
    # path('post/<pk>/delete/', post_delete, name='post_delete'),
    path('post_not_allowed', post_not_allowed, name='post_not_allowed'),

    path('post/<pk>/confirm_delete/', post_confirm_delete, name='post_confirm_delete'),
    path('post/<pk>/confirm_delete/delete/', post_delete, name='post_delete'),
    # 댓글 삭제
    path('post/<post_pk>/comment_delete/<comment_pk>', comment_delete, name='comment_delete'),
]

post/models.py
from django.db import models
from django.conf import settings
from django.utils import timezone

class Category(models.Model):
    name = models.CharField(max_length=50, unique=True)
    slug = models.SlugField(max_length=200, unique=True, allow_unicode=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = 'Categories'



class Post(models.Model):
    number = models.AutoField(primary_key=True)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    text = models.TextField()
    published_date = models.DateTimeField(blank=True, null=True)

    category = models.ForeignKey(Category, null=True, blank=True,on_delete=models.SET_NULL)

    # class Meta:
    #     permissions = [
    #         ('can_answer', 'Can Answer')
    #     ]

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.number.__str__()
        return self.title
        return self.text

class Comment(models.Model):
  number = models.AutoField(verbose_name='댓글 번호',primary_key=True)
  post = models.ForeignKey(Post, on_delete=models.CASCADE, null=True)
  author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True)
  body = models.TextField()
  date = models.DateTimeField(default=timezone.now)

post/forms.py
from django import forms
from .models import Post

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('category','title', 'text')
        widgets = {
            'category': forms.Select(attrs={'class': 'form-control'}),
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'text': forms.Textarea(attrs={'class': 'form-control'})
        }

        labels = {
            'category': '카테고리',
            'title': '제목',
            'text': '내용'
        }

    #title = forms.CharField(error_messages={'required': '제목을 입력하세요.'}, max_length=100, label="제목")
    #text = forms.CharField(error_messages={'required': '내용을 입력하세요.'}, widget=forms.Textarea, label="내용")

post/views.py
from django.contrib.auth.decorators import login_required, permission_required
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy
from django.utils import timezone
from django.core.paginator import Paginator

from .models import Post, Comment, Category
from .forms import PostForm
from django.http import HttpResponse

def post_delete(request, pk):
    post = get_object_or_404(Post, pk=pk)

    if request.user != post.author:
        return render(request, 'post/post_not_allowed.html')

    if request.method == 'POST':
        post = Post.objects.get(pk=pk)
        post.delete()
        return render(request, 'post/post_delete.html')

    elif request.method == 'GET':
        return HttpResponse('잘못된 접근 입니다.')

def post_list(request):
    posts = Post.objects.all(published_date__lte=timezone.now()).order_by('-published_date')
    return render(request, 'post/post_list.html', {'posts': posts})

def post_list_notice(request):
    posts = Post.objects.filter(published_date__lte=timezone.now(), category__name='공지').order_by('-published_date')
    return render(request, 'post/post_list_notice.html', {'posts': posts})

def post_list_questions(request):
    posts = Post.objects.filter(published_date__lte=timezone.now(), category__name='질문').order_by('-published_date')
    return render(request, 'post/post_list_questions.html', {'posts': posts})

def post_list_request(request):
    posts = Post.objects.filter(published_date__lte=timezone.now(), category__name='요청').order_by('-published_date')
    return render(request, 'post/post_list_request.html', {'posts': posts})

def post_list_report(request):
    posts = Post.objects.filter(published_date__lte=timezone.now(), category__name='제보').order_by('-published_date')
    return render(request, 'post/post_list_report.html', {'posts': posts})

def post_list_etc(request):
    posts = Post.objects.filter(published_date__lte=timezone.now(), category__name='기타').order_by('-published_date')
    return render(request, 'post/post_list_etc.html', {'posts': posts})

def post_detail(request, pk):
    post_detail = get_object_or_404(Post, pk=pk)
    comments = Comment.objects.filter(post=pk)
    if request.method == "POST":
        comment = Comment()
        comment.post = post_detail
        comment.body = request.POST['body']
        comment.date = timezone.now()
        comment.author = request.user
        comment.save()
    return render(request, 'post/post_detail.html', {'post': post_detail, 'comments': comments})

def post_new(request):
    if request.method == "POST":
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.published_date = timezone.now()
            post.save()
            return redirect('post:post_detail', pk=post.pk)
    else:
        form = PostForm()

    return render(request, 'post/post_edit.html', {'form': form})

def post_edit(request, pk):
    post = get_object_or_404(Post, pk=pk)

    if request.user != post.author:
        return render(request, 'post/post_not_allowed.html')

    if request.method == "POST":
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.published_date = timezone.now()
            post.save()
            return redirect('post:post_detail', pk=post.pk)
    else:
        form = PostForm(instance=post)

    return render(request, 'post/post_edit.html', {'form': form})

def post_not_allowed(request):
    return render(request, 'post/post_not_allowed.html')


def post_list(request):
    if not request.user.is_authenticated:
        return render(request, 'post/post_must_login.html')
    else:

        page = request.GET.get('page', '1')  # 페이지

        # 조회
        question_list = Post.objects.order_by('-published_date')

        # 페이징처리
        paginator = Paginator(question_list, 10)  # 페이지당 10개씩 보여주기
        page_obj = paginator.get_page(page)

        context = {'posts': page_obj}

        posts = Post.objects.filter(published_date__lte=timezone.now()).order_by('-published_date')

        search_key = request.GET.get('search_key')
        if search_key:  # 만약 검색어가 존재하면
            posts = posts.filter(title__icontains=search_key)  # 제목에 해당 검색어를 포함한 queryset 가져오기
            return render(request, 'post/post_list.html', {'posts': posts})

        return render(request, 'post/post_list.html', context)

def post_confirm_delete(request, pk):
    post = get_object_or_404(Post, pk=pk)

    if request.user != post.author:
        return render(request, 'post/post_not_allowed.html')

    if request.method == 'POST':
        post = Post.objects.get(pk=pk)
        return render(request, 'post/post_confirm_delete.html')

    elif request.method == 'GET':
        post = Post.objects.get(pk=pk)
        return render(request, 'post/post_confirm_delete.html')

# 댓글 삭제
def comment_delete(request, post_pk, comment_pk):
    post = get_object_or_404(Post, pk=post_pk)
    comment = get_object_or_404(Comment, pk=comment_pk)

    if request.user != comment.author:
        return render(request, 'post/post_not_allowed.html')

    if request.method == 'POST':
        comment = Comment.objects.get(pk=comment_pk)
        comment.delete()
        return render(request, 'post/comment_delete.html')

    elif request.method == 'GET':
        comment = Comment.objects.get(pk=comment_pk)
        comment.delete()
        return render(request, 'post/comment_delete.html')

post/templates/post/comment_delete.html
{% extends "post/post_base.html" %}

{% block content %}
<style>
.mustlogin {
    font-size: 17px;
    font-weight: bolder;
    text-align: center;
    color: #57B59A;
}
/*색상 변경 코드 추가*/
.btn-outline-success:active,
.btn-outline-success:visited,
.btn-outline-success:active:focus,
.btn-outline-success:active:hover {
    border-color: #57B59A;
    background-color: #57B59A;
    }

    {
        margin:0 auto;
        padding:0;
        border:0;
        font: 맑은고딕;
        text-decoration:none;
        letter-spacing:0px;
    }
    html {height:100%;}

    .buttons{
        margin: 0 auto;
        text-align:center;
    }
</style>
<head><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.8.2/css/all.min.css"/></head>
<body>
    <br/>
    <div class="mustlogin">
        <p>댓글이 삭제되었습니다.</p>
        <div class="buttons">
        <a href="/">
            <a class="btn btn-outline-success" href="{% url 'post:post_list' %}" style ="margin-top:35px;"><i class="fas fa-list"> 목록</i></a>
        </a>
        </div>
    </div>
</body>
{% endblock %}

post/templates/post/post_confirm_delete.html
{% extends "post/post_base.html" %}
{% block title %}- Confirm Delete{% endblock %}

{% block content %}
<head><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.8.2/css/all.min.css"/></head>
<form action="delete/" method="POST">
    {% csrf_token %}
    <div class="alert alert-danger">글을 정말로 삭제하시겠습니까?</div>
    <button type="submit" class="btn btn-outline-danger"><i class="fas fa-trash-alt"> 삭제</i></button>
<!--    <input type="submit" value="삭제" class="btn btn-outline-danger">-->
    <a class="btn btn-outline-secondary" onclick="history.back()"><i class="fas fa-times"> 취소</i></a>
</form>
{% endblock %}

post/templates/post/post_delete.html
{% extends "post/post_base.html" %}

{% block content %}
<style>
.mustlogin {
    font-size: 17px;
    font-weight: bolder;
    text-align: center;
    color: #57B59A;
}
/*색상 변경 코드 추가*/
.btn-outline-success:active,
.btn-outline-success:visited,
.btn-outline-success:active:focus,
.btn-outline-success:active:hover {
    border-color: #57B59A;
    background-color: #57B59A;
    }

    {
        margin:0 auto;
        padding:0;
        border:0;
        font: 맑은고딕;
        text-decoration:none;
        letter-spacing:0px;
    }
    html {height:100%;}

    .buttons{
        margin: 0 auto;
        text-align:center;
    }
</style>
<head><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.8.2/css/all.min.css"/></head>
<body>
    <br/>
    <div class="mustlogin">
        <p>글이 삭제되었습니다.</p>
        <a href="/">
            <a class="btn btn-outline-success" href="{% url 'post:post_list' %}" style ="margin-top:25px;"><i class="fas fa-list"> 목록</i></a>
        </a>
    </div>
</body>
{% endblock %}

post/templates/post/post_detail.html
{% extends "post/post_base.html" %}

{% block content %}
<style>
/* 데스크탑 */
#submit-btn { margin-top:0.6%;width:9%;float:right;}
#textarea {width:89%;}

@media screen and (max-width:1023px) {
/* 타블렛 */
#submit-btn {width:13%; margin-top:1.2%;float:right;}
#textarea{ width:85%;}
}

@media screen and (max-width:767px) {
/* 모바일 */
#submit-btn {width:20%; margin-top:1.5%;float:right;}
#textarea{ width:79%;}
}


</style>


<head><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.8.2/css/all.min.css"/></head>
<body>
<br/><br/><br/><br/>
    <div class="container">
        <form action="delete/" method="POST" style="float:right; margin-top:0;">
            {% csrf_token %}
            <a class="btn btn-outline-primary" href="{% url 'post:post_list' %}" style ="float:left; margin-top:25px;margin-left:5px;"><i class="fas fa-list"> 목록</i></a>
            {% if user == post.author %}
            <a class="btn btn-outline-success" href="edit/" style="float:left;margin-top:25px;margin-left:5px;"><i class="fas fa-edit"> 수정</i></a>
            <a class="btn btn-outline-danger" href="confirm_delete/" style="float:left;margin-top:25px;margin-left:5px;"><i class="fas fa-trash-alt"> 삭제</i></a>
            {% endif %}
        </form>
        <h4>{{ post.number }}</h4>
        <h3><a href="" style="text-decoration:none; color:#57B59A;">{{ post.title }}</a></h3>
        <div class="text">{{ post.text|linebreaksbr }}</div>
    </div>

<br/><br/>
    <div class="container">
        <div class="card my-4">
            <h5 class="card-header">댓글  <i class="fas fa-comment"></i></h5>
        <div class="card-body">
            <form method="POST">
                {% csrf_token %}
                <textarea name="body" type="text" value="" id ="textarea" rows=3></textarea>
                <button type="submit" id = "submit-btn" class="btn btn-outline-secondary">댓글<br/>등록</button>
            </form>
        </div>
        </div>
    <br/>
    {% for comment in comments %}
        {% if request.user == comment.author %}
        <strong><a href="comment_delete/{{ comment.pk }}" style="float:right; text-decoration:none;"><i class="fas fa-trash-alt"> 삭제</i></a></strong>
        {% endif %}
        <strong>{{comment.author}}</strong><br/>
        <br/>{{comment.body}}
        <p style="float:right; font-size:13px;">{{comment.date}}</p>
    <hr/>
    {% endfor %}
    {% csrf_token %}
    </div>
</body>
{% endblock %}

post/templates/post/post_edit.html
{% extends "post/post_base.html" %}

{% block content %}
<style>
.postbox {
    width: 100%;
    text-align: center;
    font-size:20px;
    border: 2px solid #EAEAEA;
    border-radius: 40px;
    padding: 10%;
    background: #FDFFFF;
}
:root {
  --button-color: #ffffff;
  --button-bg-color: #57B59A;
  --button-hover-bg-color: #57B59A;
}
#button1:hover{
    background: var(--button-bg-color);
    color: var(--button-color);
}
</style>
<head><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.8.2/css/all.min.css"/></head>
<body>
<div class="postbox">
    <br>
    <form method="POST" class="post-form">
        {{ form.as_p }}
        {% csrf_token %}
        <br/><br/>
        <button id="button1" type="submit" href="{% url 'post:post_list' %}" class="btn btn-outline-success"><i class="fas fa-pen"> 등록</i></button>
        <a class="btn btn-outline-secondary" href="/post/post_list"><i class="fas fa-times"> 취소</i></a>
    </form>
</div>
</body>
{% endblock %}

post/templates/post/post_list.html
{% extends "post/post_base.html" %}
{% block content %}

<style>
/* 데스크탑 */
.container {
    margin-bottom: 10px;
}

a:hover {
    text-decoration: none;
}

.item {
    overflow: hidden;
    padding-bottom: 10px;
    border-bottom: 1px solid #ddd;
}

.item h3 {
    font-weight: bolder;
}

.info {
    display: inline-block;
    float: right;
    font-size: 13px;
    color: #707070;
    margin-top: 10px;
}

.info span {
    font-weight: bold;
}

<!--.author {-->
<!--    float: right;-->
<!--}-->

.text-ellipsis {
      width: 400px;
      overflow: hidden;
      text-overflow: ellipsis;
      white-space: nowrap;
}

.td-title {
      width: 150px;
      overflow: hidden;
      text-overflow: ellipsis;
      white-space: nowrap;
}

table {
    width: 100%;
}

.table {
    border-collapse: separate;
}

.buttonbox {
    width:100%;
    height: 10px;
}

.writebutton{
    float:right;
}

.searchbutton{
    float:right;
    position:relative;
}

.searchbutton img{
    position: absolute;
    left: 215px;
    top:9px;
}

.divpop {
    position: absolute; z-index:999; top:50%; left:50%;
    width:500px;     height: 50%; display:none;
    transform: translate(-50%,-50%);
    min-width: 300px;
    max-width: 100%;
    background-color: #fff;
    border-radius: 15px;
    box-shadow: 0 2px 55px -25px rgb(0 0 0 / 100%);
  }

.title_area {
      padding: 20px;
      box-sizing: border-box;
      width:100%;
}

.button_area {position:absolute;bottom:0;left:10px;}

.title{
    border-radius: 15px 15px 0 0;
    min-height: 40px;
    color: #fff;
    background-color: #57B59A;
    padding: 10px 15px;
    box-sizing: border-box;
    font-weight: bold;
}

/* 타블렛 */
@media screen and (max-width:1023px) {
   #text-ellipsis, .text-ellipsis      { overflow:hidden; text-overflow:ellipsis; white-space:nowrap;width:300px;}
   #td-title, .td-title      { overflow:hidden; text-overflow:ellipsis; white-space:nowrap;width:100px;}
   #td-date, .td-date      { overflow:hidden; text-overflow:ellipsis; white-space:nowrap;width:100px;}
   #td-author, .td-author      { overflow:hidden; text-overflow:ellipsis; white-space:nowrap;width:80px;}
   .searchbutton img{position:absolute;left:217px;top:15px;}
}

/* 모바일 */
@media screen and (max-width:767px) {
   #text-ellipsis, .text-ellipsis      { overflow:hidden; text-overflow:ellipsis; white-space:nowrap;width:150px;}
   #td-title, .td-title      { overflow:hidden; text-overflow:ellipsis; white-space:nowrap;width:90px;}
   #td-date, .td-date      { overflow:hidden; text-overflow:ellipsis; white-space:nowrap;width:50px;}
   #td-author, .td-author      { overflow:hidden; text-overflow:ellipsis; white-space:nowrap;width:50px;}
   .searchbutton img{position:absolute;left:217px;top:15px;}
}
</style>
<body >
<form name="notice_form">
   <div id="divpop1" class="divpop">
          <div class="title">게시판 페이지 공지사항</div>
      <div class="title_area">
            <P> 게시판 페이지 공지사항에 대해 안내 드리겠습니다.
                <br> 게시판 유형은 공지 | 질문 | 요청 | 제보 | 기타
                <br> 5가지로 구분되어 있습니다.
            </P>
            <p>
                공지 : 관리자가 공지할 사항을 작성한 게시글<br>
                질문 : 흡연구역 & 시각화에 대한 질문에 대한 게시글<br>
                요청 : 흡연구역 & 시각화에 대한 요청에 대한 게시글<br>
                제보 : 등록된 흡연구역 이외의 흡연구역 위치 제보에 대한 게시글<br>
                기타 : 이외 게시글<br><br>
                사이트 이용시 참고해 주시기 바랍니다. 감사합니다.
            </p>
        </div>
       <div class="button_area">
          <input type='checkbox' name='chkbox' id='todaycloseyn' value='Y'>오늘 하루 이 창을 열지 않음
          <a href='#' style="color:#57B59A"; onclick="javascript:closeWin(1);"><B>[닫기]</B></a>
       </div>
   </div>
</form>
<script>
//쿠키설정
   function setCookie( name, value, expiredays )
   {
    var todayDate = new Date();
    todayDate.setDate( todayDate.getDate() + expiredays );
    document.cookie = name + '=' + escape( value ) + '; path=/; expires=' + todayDate.toGMTString() + ';'
   }

   //쿠키 불러오기
   function getCookie(name)
   {
       var obj = name + "=";
       var x = 0;
       while ( x <= document.cookie.length )
       {
           var y = (x+obj.length);
           if ( document.cookie.substring( x, y ) == obj )
           {
               if ((endOfCookie=document.cookie.indexOf( ";", y )) == -1 )
                   endOfCookie = document.cookie.length;
               return unescape( document.cookie.substring( y, endOfCookie ) );
           }
           x = document.cookie.indexOf( " ", x ) + 1;
           if ( x == 0 )
               break;
       }
       return "";
   }

   //닫기 버튼 클릭시
   function closeWin(key)
   {
       if($("#todaycloseyn").prop("checked"))
       {
           setCookie('divpop'+key, 'Y' , 1 );
       }
       $("#divpop"+key+"").hide();
   }

   $(function(){

      if(getCookie("divpop1") !="Y"){
         $("#divpop1").show();
      }

   });;
</script>

<div class="container">

  <div class="buttonbox">
        <!--글쓰기 기능을 위한 버튼-->
        <div class="writebutton">
            <a href="{% url 'post:post_new' %}">
            <button class="btn my-2 my-sm-0">
                <img style="width:22px;height:22px;" src="https://user-images.githubusercontent.com/73421028/133558544-baeabe75-999d-415b-8f02-746b2293d5e6.png">
            </button>
            </a>
        </div>

        <!-- 검색 기능을 위한 검색 창과 버튼-->
        <div class="searchbutton">
            <form action="" method="GET" class="form-inline my-2 my-lg-0">
                <button class="btn my-2 my-sm-0" type="submit">
                    <img style="width:22px;height:22px;" src="https://user-images.githubusercontent.com/73421028/133556991-e1de119a-40b5-4276-b980-9254d9ee5af3.png">
                </button>
                <input class="form-control mr-sm-2" style="width:220px;" name="search_key" value="{{ search_key }}" type="text" placeholder="검색어를 입력해주세요" aria-label="Search">
            </form>
        </div>
  </div>

    <br/>
    <div class="row mt-5">
        <div class="col-12">
        </div>
        <table class="table" cellspacing="0">
            <thead class="thead">
                <tr>
                    <th scope="col">&nbsp;&nbsp;</th>
                    <th scope="col">
                    <div class="dropdown" style="text-align:center;height:30px;">
                        <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-expanded="true">
                            <strong>유형</strong>
                        </button>
                        <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1">
                            <li role="presentation"><a role="menuitem" tabindex="-1" href="{% url 'post:post_list_notice' %}" style="margin-left:10px;color:black">공지</a></li>
                            <div class="dropdown-divider"></div>
                            <li role="presentation"><a role="menuitem" tabindex="-1" href="{% url 'post:post_list_questions' %}" style="margin-left:10px;color:black">질문</a></li>
                            <div class="dropdown-divider"></div>
                            <li role="presentation"><a role="menuitem" tabindex="-1" href="{% url 'post:post_list_request' %}" style="margin-left:10px;color:black">요청</a></li>
                            <div class="dropdown-divider"></div>
                            <li role="presentation"><a role="menuitem" tabindex="-1" href="{% url 'post:post_list_report' %}" style="margin-left:10px;color:black">제보</a></li>
                            <div class="dropdown-divider"></div>
                            <li role="presentation"><a role="menuitem" tabindex="-1" href="{% url 'post:post_list_etc' %}" style="margin-left:10px;color:black">기타</a></li>
                        </ul>
                    </div>
                    </th>
                    <th scope="col">제목</th>
                    <th scope="col">내용</th>
<!--                    <th scope="col">작성일</th>-->
                    <th scope="col">작성자</th>
                </tr>
            </thead>

            <tbody class="tbody">
            {% for post in posts %}
            <tr onclick = "location.href='post/{{ post.pk }}/'">
                <th scope="row">
                    {{ post.number }}
                </th>
                {#카테고리#}
                <td width="50px" style="word-break:break-all;text-align:center"><div class="td-title">
                    {% if post.category.name == '공지' %}
                        <span >{{post.category}}</span>
                    {% elif post.category.name == '질문' %}
                        <span>{{post.category}}</span>
                    {% elif post.category.name == '요청' %}
                        <span >{{post.category}}</span>
                    {% elif post.category.name == '제보' %}
                        <span >{{post.category}}</span>
                    {% elif post.category.name == '기타' %}
                        <span >{{post.category}}</span>
                    {% endif %}
                </div></td>

                <td width="250px" style="word-break:break-all"><div class="td-title">
{#                    링크 수정 : 글번호 --> 제목#}
                    <a  style="text-decoration:none; color:#57B59A;"  href='post/{{ post.pk }}/'>
                        {{ post.title }}
                    </a>
                </div></td>
                <td width="500px" style="word-break:break-all"><div class="text-ellipsis">{{ post.text }}</div></td>
<!--                <td width="250px" style="word-break:break-all"><div class="td-date">{{ post.published_date }}</div></td>-->
                <td width="200px" style="word-break:break-all"><div class="td-author">{{ post.author }}</div></td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
        <!-- 페이징처리 시작 -->

    </div>
</div>


<div class="paging">
        <ul class="pagination justify-content-center">
        <!-- 이전페이지 -->
        {% if posts.has_previous %}
        <li class="page-item">
            <a class="page-link" style="text-decoration:none; color:#57B59A;" href="?page={{ posts.previous_page_number }}">이전</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
        </li>
        {% endif %}
        <!-- 페이지리스트 -->
        {% for page_number in posts.paginator.page_range %}
            {% if page_number == posts.number %}
                <li class="page-item" aria-current="page">
                    <a class="page-link" style="text-decoration:none; color:#57B59A;" href="?page={{ page_number }}">{{ page_number }}</a>
                </li>
            {% else %}
                <li class="page-item">
                    <a class="page-link" style="text-decoration:none; color:black;" href="?page={{ page_number }}">{{ page_number }}</a>
                </li>
            {% endif %}
        {% endfor %}
        <!-- 다음페이지 -->
        {% if posts.has_next %}
        <li class="page-item">
            <a class="page-link" style="text-decoration:none; color:#57B59A;" href="?page={{ posts.next_page_number }}">다음</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
        </li>
        {% endif %}
        </ul>
        <!-- 페이징처리 끝 -->
</div>

</body>
{% endblock %}

post/templates/post/post_must_login.html
{% extends "post/post_base.html" %}

{% block content %}
<style>
.mustlogin {
    font-size: 17px;
    font-weight: bolder;
    text-align: center;
    color: #57B59A;
}
/*색상 변경 코드 추가*/
.btn-outline-success:active,
.btn-outline-success:visited,
.btn-outline-success:active:focus,
.btn-outline-success:active:hover {
    border-color: #57B59A;
    background-color: #57B59A;
    }

    {
        margin:0 auto;
        padding:0;
        border:0;
        font: 맑은고딕;
        text-decoration:none;
        letter-spacing:0px;
    }
    html {height:100%;}

    .buttons{
        margin: 0 auto;
        text-align:center;
    }


</style>
<head><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.8.2/css/all.min.css"/></head>
<body>
    <br/> <br/> <br/> <br/> <br/>
    <div class="mustlogin">
<!--        버튼 색상 호버 색상 변경-->
        <p>해당 메뉴는 로그인한 회원만 사용 가능합니다.</p>
        <div class="buttons">
        <a class="btn btn-outline-success" href="{% url 'accounts:login' %}" style ="margin-top:35px;margin-right:10px;"><i class="fas fa-user"> 로그인</i></a>
        <a class="btn btn-outline-success" href="{% url 'accounts:register' %}" style ="margin-top:35px;"><i class="fas fa-user-plus"> 회원가입</i></a>
        </div>
    </div>
</body>
{% endblock %}